import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auth title",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="grid h-screen sm:place-items-center bg-gray-200">
     <div className="rounded shadow-xl  bg-white w-full overflow-hidden  sm:w-3/12">
     {children}
     </div>
    </div>
  );
};

export default Layout;